// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnzzxglceldyummkwqbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impuenp4Z2xjZWxkeXVtbWt3cWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODEwMzIsImV4cCI6MjA2MDU1NzAzMn0.AmM7_eOpQflJEKZBUx9iWeTD5pjvxH1y9ziSEXpLb7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);